// import express
const express = require('express') ;
// import body-parser
const bodyParser = require('body-parser');

// initialize an express instance
const app = express();
// let bodyParser to parse JSON, under the hook of express 
app.use(bodyParser.json());

// define port of listening
const port = 3000;

// add some data to this web server app
let movies = [
    { id: '1588323375416', title: 'Star Wars: Episode IX - The Rise of Skywalker', year: 2019, director: 'J.J. Abrams' },
    { id: '1588323390624', title: 'The Irishman', year: 2019, director: 'Martin Scorsese' },
    { id: '1588323412643', title: 'Harry Potter and the Sorcerers Stone', year: 2001, director: 'Chris Columbus' }
];

// specify "endpoint", add GET method
app.get("/api/movies", (req, res) => {
    res.json(movies);
});

// attache webserver event listener to port, interact with user requests
app.listen(port, () => {
    console.log(`Server is running on port ${port}.`);
});

// implement GET {id} functionality, which can be used to search movie by id.
app.get("/api/movies/:id", (req, res) =>{
    // get target movieID from request parameter
    let movieID = req.params.id;
    
    // "filter" creates a new array
    // iterates through the array and invokes the argument function to all elements
    let movie = movies.filter(movie => movie.id === movieID);

    // specify the response
    if (movie.length > 0)
        res.json(movie);
    else
        res.sendStatus(404); //print out "Not Found" on browser.
});

// implement POST to'end point', for adding new movie to the web server app
app.post("/api/movies", (req, res) => {
    // extract a movie object from req.body specified in spread syntax
    // here we use POSTMAN body to get post request in json form
    // id is generated by Date.now() 
    let newMovie = {'id': Date.now(), ...req.body};

    // add newMovie object to the end of movies array
    movies = [...movies, newMovie]

    // specify response
    res.json(movies);
})